spring:
  properties:
    host-name: localhost
    feature-enabled:
      auto-upload: false
      feed-generation: false
    email:
      username: ${EMAIL_USERNAME:test}
      password: ${EMAIL_PASSWORD:test}

logging:
  level:
    root: info
    com:
      github:
        regyl:
          gfi:
            service:
              impl:
                feed:
                  cyclonedx:
                    CycloneDxSbomConsumerImpl: INFO
                    homepage:
                      maven:
                        MavenPurlToBuildFileServiceImpl: INFO