services:
  postgres:
    image: 'postgres:15.3'
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'idk_user'
      POSTGRES_PASSWORD: 'SomeUselessPassword02'
      POSTGRES_DB: 'uj'
  cdxgen-0:
    image: ghcr.io/cyclonedx/cdxgen:v11.11.0
    container_name: cdxgen-0
    ports:
      - '9090:9090'
    environment:
      CDXGEN_DEBUG_MODE: "debug"
    command: >
      cdxgen
      --no-babel
      --server
      --server-host 0.0.0.0
      --server-port 9090
  cdxgen-1:
    image: ghcr.io/cyclonedx/cdxgen:v11.11.0
    container_name: cdxgen-1
    ports:
      - '9091:9090'
    environment:
      CDXGEN_DEBUG_MODE: "debug"
    command: >
      cdxgen
      --no-babel
      --server
      --server-host 0.0.0.0
      --server-port 9090
  cdxgen-2:
    image: ghcr.io/cyclonedx/cdxgen:v11.11.0
    container_name: cdxgen-2
    ports:
      - '9092:9090'
    environment:
      CDXGEN_DEBUG_MODE: "debug"
    command: >
      cdxgen
      --no-babel
      --server
      --server-host 0.0.0.0
      --server-port 9090
  cdxgen-3:
    image: ghcr.io/cyclonedx/cdxgen:v11.11.0
    container_name: cdxgen-3
    ports:
      - '9093:9090'
    environment:
      CDXGEN_DEBUG_MODE: "debug"
    command: >
      cdxgen
      --no-babel
      --server
      --server-host 0.0.0.0
      --server-port 9090
  cdxgen-4:
    image: ghcr.io/cyclonedx/cdxgen:v11.11.0
    container_name: cdxgen-4
    ports:
      - '9094:9090'
    environment:
      CDXGEN_DEBUG_MODE: "debug"
    command: >
      cdxgen
      --no-babel
      --server
      --server-host 0.0.0.0
      --server-port 9090