version: '3.9'

services:
  postgres:
    image: 'postgres:15.3'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'idk_user'
      POSTGRES_PASSWORD: 'SomeUselessPassword02'
      POSTGRES_DB: 'uj'